version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: arostream-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - redis

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: arostream-queue
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: arostream-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: arostream-postgres
    environment:
      POSTGRES_DB: arostream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: arostream-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
